NASA-NAVO/navo-workshop

00_SETUP.md, check_env.py, environment.yml
Since pyvo 1.1 has been released, this PR is primarily to update the environment file.
It is likely to require changes also to `00_SETUP.md` and perhaps `KNOWN_ISSUES.md`.~~, and I just realized we do not have `check_env.py` on the master branch.~~ (now we do have `check_env.py` from #2).
=> Update package versions to account for pyvo 1.1 release

.circleci/config.yml, .circleci/dev-requirements.txt, environment.yml
Following the setup for the [astropy-workshop repository](https://github.com/astropy/astropy-workshop), add files for continuous integration with CircleCI.
Fixes #12
=> Add continuous integration for notebooks

check_env.py
Updates to `check_env.py`:
* Remove scikit-image from the packages to check
* Update minimum versions
Fixes #30
=> update versions and packages to check

CS_Catalog_Queries.ipynb, CS_UCDs.ipynb
Issue #27  should be fixed.  It's from the service, so now there's just more error trapping.  A few misc. improvements.
=> Modified CS_UCD to recover from service issues.  Some rewording.

00_SETUP.md
from `navo-workshop` to `navo-env` to match the recent environment name change in `environment.yml`.
=> Change environment name references in setup doc

check_env.py, environment.yml
Update conda environment.
* python=3.8
* pin pyvo to the latest commit today, pending a v1.2 release
* remove unused packages
=> updates to trim packages and update versions

KNOWN_ISSUES.md, QuickReference.ipynb, UseCase_I.ipynb, UseCase_II.ipynb, UseCase_III.ipynb
- Minor changes to clean up the long urls by using a descriptive text.
- Enabled scroll for cells with long output.
=> Clean up the long urls

Exercise_III.ipynb, UseCase_III.ipynb
Cleaning up UseCaseIII and added empty Exercise workbook for WS, as discussed. This Use Case should now be ready to go!
=> Fix use case iii

00_SETUP.md, QuickReference.ipynb, README.md
This should come with renaming the default branch in the repo "Settings"
=> master --> main branch rename

Exercise_I.ipynb, QuickReference.ipynb, UseCase_I.ipynb
=> Update astroquery.ipac module namespaces

Exercise_I.ipynb, UseCase_I.ipynb
=> Fix to issue #77

.binder/requirements.txt, CS_Image_Access.ipynb, Exercise_II.ipynb, UseCase_I.ipynb, UseCase_II.ipynb, UseCase_III.ipynb, check_env.py, environment.yml, tox.ini
Doing a fresh PR so it is easier to see the new code changes.
=> Updates to the notebooks to work with the new registry interface

Exercise_I.ipynb
Suggestions for Exercise_I comments (issue #83)
=> Adding more comments to Exercise I

KNOWN_ISSUES.md
=> Updates to known issues

.github/workflows/ci_tests_and_publish.yml
to close https://github.com/NASA-NAVO/navo-workshop/issues/101
=> CI: adding environment.yml file to CI testing

UseCase_I.ipynb
This is a fix for issue #128, where the column name used in UseCase_1 appear to have changed from `enrValue` to `energy_bounds_center`.
I found also that in order to get the correct file, I had to add `productType == 'SCIENCE'`.
=> fix the column name in Galex table in UseCase_1 (issue #128)

.binder/requirements.txt, check_env.py, environment.yml, tox.ini
This should fix the caching issue
cc @tomdonaldson @stargaser
=> Use the latest astroquery from pip

00_SETUP.md
=> Add Windows WSL instructions [skip ci]

content/reference_notebooks/basic_reference.md, content/reference_notebooks/catalog_queries.md, content/reference_notebooks/image_access.md, content/reference_notebooks/spectral_access.md, content/reference_notebooks/ucds_unified_content_descriptors.md, content/reference_notebooks/votables.md, content/use_case_notebooks/candidate_list_exercise.md, content/use_case_notebooks/candidate_list_solution.md, content/use_case_notebooks/hr_diagram_exercise.md, content/use_case_notebooks/hr_diagram_solution.md, content/use_case_notebooks/proposal_prep_exercise.md, content/use_case_notebooks/proposal_prep_solution.md, index.md
I modified the top-level header of each content notebook md file to match the file names.  I also updated index.md to give a little more organization to the list of notebooks.
Apologies for my VS Code editor removing some trailing whitespace and changing the bullet character.  I also inadvertently modified some of the notebook metadata ( like Python and jupytext version).  
Some possible future items:
- I wish the sidebar retained more of the hierarchical structure and depth of the main table of contents, but I couldn't quickly see how to do that.
- I noticed the the VO Tables reference notebook contains some confusing things.  I guess it's helpful if you're creating a table upload, otherwise I would just remove it for now.
=> Modify notebook headers to match file names; update index.md

.github/workflows/circleci-artifacts-redirector.yml
=> CI: update action that got moved org

.github/dependabot.yml, .github/workflows/ci_tests_and_publish.yml
So these updates will come automatically
=> MAINT: update actions' version and add dependabot

.github/workflows/ci_tests_and_publish.yml, tox.ini
closes #169 by retesting for flaky servers and closes #183 by adding names to conda testing steps.
=> CI: various enhancements to how we test

00_SETUP.md
=> Update miniconda installation link
