CS_Image_Access.ipynb, KNOWN_ISSUES.md, UseCase_I.ipynb, UseCase_II.ipynb, environment.yml
The astropy 4.1 release includes the fixes to `astropy.io.votable` by @tomdonaldson that previously caused byte columns to be returned in Astropy tables. The changes in this pull request alter the handful of cases where we showed selection using byte strings, to remove these tests. These code changes should make the notebooks work with both astropy 4.1 and with previous versions.
Some additional cleanup of whitespace and wording in `KNOWN_ISSUES.md` has also been done, as well as suppressing a new warning from importing aplpy in the CS_Image_Access notebook.
=> Remove instances of testing against byte strings

QuickReference.ipynb, environment.yml
and also work around GALEX image search issue in QuickReference.ipynb by using a different service. (see #26 )
For AAS 238, we would like to lock the versions of pyvo and astroquery to be recent versions from their master branches, while keeping the version fixed to ensure stability throughout the workshop.
For pyvo, lock the version at this PR merge since we will use the functionality from that PR:  https://github.com/astropy/pyvo/commit/c7a2ebad95629932775fb0966a6a79aec23b6dda
For astroquery, lock the version at the most recent PR merged.  We don't specifically need that functionality, but want to be up to date with close to the latest prerelease version since v0.4.1 is quite old.  NB there is a known pip installation issue (https://github.com/astropy/astroquery/issues/1920) with …
=> Lock pyvo and astroquery versions for AAS 238

.gitignore, environment.yml
Astroquery 0.4.2 was release shortly after we pinned the astroquery version to the head of the main github branch, so unpinning will give us all the same functionality without the hacky `environment.yml`.
Also gitignored the `_build` directory which is created if one uses the `nbcollection` package to execute the notebooks from the command line.
=> Unpin astroquery version (0.4.2 released), and ignore _build directory

CS_Catalog_Queries.ipynb, CS_UCDs.ipynb
Some reworking to clarify how to search for catalogs served by TAP with the includeaux, and alternate ways to look at tables from a given service, etc.  Note that the last query is broken for async for reasons unknown so it has been set back to the sync.
=> Tjissue16:  update data discovery in Catalogs cheat sheet

QuickReference.ipynb
KOA has an astroquery-compliant module (pyKOA) that was developed for astroquery.
It has been added to the quick reference as astroquery-compliant and has a link to the KOA page with examples on how to use the pyKOA module.
=> Add KOA to Quick Reference

CS_Image_Access.ipynb
As a holdover from when the result VOTables string values were  `bytes` instead of `str`, we were filtering a table for `short_name` containing `b'SDSSDR7'` and not finding any.  This didn't mess up the next step since repeated the filtering with `'SDSSDR7'`, but the fact that no results were found in the first filter was messy and confusing.
Fixes #36
=> Remove byte string from comparison

.binder/requirements.txt, .circleci/config.yml, .github/workflows/circleci-artifacts-redirector.yml, .github/workflows/publish_docs.yml, conf.py, doc-requirements.txt, index.md
This PR adds the most basic github actions config for running and deploying HTML rendering of the notebooks. It also adds the rendering job to the circleCI config without removing or cleaning up any of the existing CI.
In this first iteration all the notebooks files are rendered, naturally making a sensible selection, or changes to their order/grouping should be done, and probably is best done in a follow-up focusing on more on the content than on getting the infrastructure off the ground.
=> Enabling HTML rendering and deployment

.github/workflows/ci_tests_and_publish.yml, environment.yml, tox.ini
This is to fix #87 and hopefully it #86 (and failing CI in the other open PRs, too).
It it comes back with a full green status, I would suggest to get this merged asap.
=> Adding minimum numpy version

check_env.py, environment.yml
Fixes #105 by conda installing `astropy` from the `conda-forge` channel rather than the `astropy` channel.  `conda-forge` seems to be the only channel with the latest (`5.2`) version of `astropy`, and `5.2` is needed for compatibility with `numpy==1.24`.
Also updated the `check_env.py` script with latest versions for `astropy` and `numpy`.
=> Stop using astropy channel; only conda-forge has latest astropy

Exercise_I.ipynb, Exercise_III.ipynb, QuickReference.ipynb, UseCase_I.ipynb, UseCase_III.ipynb
This should fix #102, but I didn't add this to all the cells, only the ones that already had the `tags` metadata.
Ideally we should set the scrolling locally, but I haven't yet found a way to do it only on the cell metadata level.
=> Output scrolling

.circleci/config.yml, doc-requirements.txt
For some reason circleCI picks up a rather old sphinx-book-theme and pydata-sphinx-theme versions. This PR should fix that and the build failure (caused by a deprecation)
=> CI: fix html rendering CI job

.github/workflows/ci_devtests.yml, .github/workflows/ci_tests_and_publish.yml
To make it easier and nicer to trigger a CI run without a PR or making any changes to the repo.
=> CI: adding workflow_dispatch

00_SETUP.md, check_env.py, environment.yml
* Remove 'notebook' from `check_env.py` as it is not installed with Jupyterlab 4.0.
* Add a check for 'scipy' and a minimum version of 1.0
* Add Mambaforge as an alternative to Miniconda
* Note that the environment installation can take a while
Fixes #117
=> Update installation files and instructions

.github/workflows/circleci-artifacts-redirector.yml
Same as https://github.com/numpy/numpy-tutorials/pull/178, to fix the circleCI redirects
=> CI: adding circleCI token

.gitignore, content/reference_notebooks/catalog_queries.md, index.md, tox.ini
I see some weird errors locally when trying to render, so using this PR to smoke out whether it's a local issue or something substantial.
=> CI: using new notebooks names in README for rendering

KNOWN_ISSUES.md, content/use_case_notebooks/candidate_list_solution.md
* Remove the `format=None` from SDSS SIAP searches
* Slightly update KNOWN_ISSUES since `format=None` is no longer needed
* Remove idiosyncratic `intersect='covers'` from first SDSS image search
Fixes #38
=> Remove format=None and intersect=covers for SDSS SIAP

.github/workflows/ci_tests_and_publish.yml, tox.ini
=> CI: updating commands for conda tests

README.md
=> Add sciserver information to README

content/reference_notebooks/catalog_queries.md
This cell was failing because it assumed the table descriptions would be strings, but one (the table called `first`) was `None`.
=> Protect against None in table descriptions

00_SETUP.md
* Instruct users to first change directory to the `content` subdirectory
* Start Jupyterlab from there
* Add they can use the JLab file browser to navigate to the notebooks
Fixes #156
=> Add starting directory instructions for Jupyterlab

.github/workflows/ci_devtests.yml, .github/workflows/ci_tests_and_publish.yml
This should fix some of the warnings/errors we see, but not the content issues, so I'll go ahead and merge it if the infrastructure warnings are gone.
=> CI: update GHA versions

content/reference_notebooks/ucds_unified_content_descriptors.md, doc-requirements.txt
Fixes #162
The tap_schema for HSC changed recently to make all table and column names lower case.  The UCD notebook had a couple explicit references to those that broke when the case changed.  This PR fixes those names to get the notebook to run.
During this update I noticed that multiple things in the UCD notebook seemed incorrect.  I did not try to fix them here, but created #165 to track those problems.
=> Fix HSC table and columns names in UCD notebook

.github/workflows/ci_devtests.yml, .github/workflows/ci_tests_and_publish.yml, tox.ini
This should close #136
I would not be surprised if we run into a couple of numpy 2.0 issues, but hopefully this doesn't recover some serious issues.
=> CI: using newer versions and adding prerelease test

KNOWN_ISSUES.md, content/reference_notebooks/basic_reference.md, content/reference_notebooks/catalog_queries.md, content/reference_notebooks/image_access.md, content/use_case_notebooks/candidate_list_solution.md, content/use_case_notebooks/proposal_prep_solution.md
Proof of concept to see if how proposed changes of pyvo would look in practice
(this is just sed-ing through the code, the narrative text may need some updates, too)
(Also, I wonder why we only have `'sia'` but not `'sia1'`, as the latter would be the correct, non-ambiguous one, thus I'm opening an upstream, pyvo PR for that)
closes #170
=> MAINT: changing servicetype image/spectrum to sia/ssa

.binder/requirements.txt
we need these for `.show_in_notebook()`, but will not work with older versions. So I first use CI to smoke things and then adjust the PR.
=> DEP: adding astropy[jupyter] to pick up dependencies

content/reference_notebooks/catalog_queries.md
pyvo can work with astropy tables directly, there is no need to create all these objects
(note: this piece of unnecessary code uncovered an issue with pyvo that has now been fixed, yet I don't think there is need for this here)
=> BUG: cleanup machinery before table upload

conf.py
colab is not markdown notebook compatible, and anyway we never have had it configured up to install all the dependencies
Closes #67
=> MAINT: remove colab launch

overrides.json, postBuild
This is the alternative for #191, I use the same fix at [IRSA-tutorials](https://caltech-ipac.github.io/irsa-tutorials/) to be able to launch the markdown notebooks into binder.
Merge either this one or #191
(closes #191)
=> MAINT: fix binder launch for markdown notebooks

README.md
Each notebook identifies its kernel is `Python 3` which in Sciserver does not include the necessary dependencies such as `pyvo`.   When a notebook is opened for the first time, the kernel needs to be switched to `navo-env`.
=> Update Sciserver instructions to include switching kernels.

tox.ini
instead of last-failed as cells are not standalone. Fixes https://github.com/NASA-NAVO/navo-workshop/issues/199
=> CI: using pytest-rerunfailures

content/reference_notebooks/spectral_access.md, content/use_case_notebooks/proposal_prep_solution.md
Updated problematic cell with the following:
```python
datalink = spec_tables[0].getdatalink()
file_name = download_file(datalink.getvalue('access_url', 0),cache=True)
hdu_list = fits.open(file_name)
```
Fixes #202
=> Updated notebook to use getdatalink method

conf.py, content/reference_notebooks/basic_reference.md, content/use_case_notebooks/candidate_list_exercise.md, content/use_case_notebooks/candidate_list_solution.md, content/use_case_notebooks/hr_diagram_exercise.md, content/use_case_notebooks/hr_diagram_solution.md, doc-requirements.txt
~This PR is just a test for scroll_outputs functionality upcoming from upstream in https://github.com/executablebooks/MyST-NB/pull/683~
Fixes #102 
Undoes the #106 (since we have global config, we shouldn't hardcode scroller tag on cell level)
Test if the generated webpages have long outputs scrollable (bonus: also test dark mode style fixes that will come soon) - specifically the [Candidate List Solutions](https://output.circle-artifacts.com/output/job/a8645ce2-d3c0-46f0-8ede-c6e12e9ad527/artifacts/0/_build/html/content/use_case_notebooks/candidate_list_solution.html) (since others are ignored)
=> Enable nb_scroll_outputs from latest myst-nb
